name: Win11_LTSC2024_amd64
on:
  workflow_dispatch:
    inputs:
      iso_url:
        description: '原始ISO链接(在ntriver.org/download-windows-ltsc获取)'
        required: true
        type: string
        default: ''
      revision:
        description: '修订版本号 (例如: 26100.9445)，由changewindows.org/platforms/pc获取'
        required: true
        type: string
        default: ''
permissions:
  contents: write
env:
  REVISION: ${{ inputs.revision }}
  REVISION_NAME: Win11_LTSC2024_amd64
jobs:
  Win11_LTSC2024_amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Validate Inputs
        shell: pwsh
        run: |
          if ([string]::IsNullOrWhiteSpace("${{ inputs.iso_url }}")) {
            Write-Error "错误：ISO 下载链接不能为空！"
            exit 1
          }
          if ([string]::IsNullOrWhiteSpace("${{ inputs.revision }}")) {
            Write-Error "错误：修订版本号不能为空！"
            exit 1
          }
          Write-Host "参数校验通过。"
      - name: Step-1 Initialize Workspace
        shell: pwsh
        working-directory: .
        run: |
          mkdir -Force src
          mkdir -Force dist
      - name: Step-2 Checkout Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: .
        run: |
          git clone https://github.com/adavak/Win_ISO_Patching_Scripts.git
      - name: Step-3 Download from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        working-directory: ./Win_ISO_Patching_Scripts
        run: |
          #gh release download v1.0.0 --repo ${{ github.repository }} --pattern "*.7z.*" --dir ./
          curl -L -o win11.iso "${{ inputs.iso_url }}"
          #curl -L -o win11src.7z.001
          #7z x win11src.7z.001 -y
          #5042M
          Start-Sleep -Seconds 3
          Rename-Item -Path "*.iso" -NewName "win11.iso"
          #Remove-Item -Path "*.7z.*" -Force
          Remove-Item -Path "W10UI.ini" -Force
          Remove-Item -Path "W10UI.cmd" -Force
          ls
          pwd
          Move-Item -Path "..\set\W10UI.ini" -Destination ".\W10UI.ini" -Force
          Move-Item -Path "..\set\W10UI.cmd" -Destination ".\W10UI.cmd" -Force
          ls
          pwd
          
      - name: Step-4 Update By Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: .
        run: |
          .\Win_ISO_Patching_Scripts\Start.cmd
          
      - name: Step-5 Split Archive
        shell: pwsh
        working-directory: .
        run: |
          Remove-Item -Path ".\Win_ISO_Patching_Scripts\win11.iso" -Force
          
          $file = Get-ChildItem -Path .\Win_ISO_Patching_Scripts -Filter "*.iso" -File | Select-Object -First 1
          $fileNameOnly =$file.Name
          $fullPath =$file.FullName
          Add-Content -Path $env:GITHUB_ENV -Value "FINAL_ARTIFACT_NAME=$fileNameOnly"
          Add-Content -Path $env:GITHUB_ENV -Value "FINAL_ARTIFACT_PATH=$fullPath"
          Write-Host "捕获到的文件名: $fileNameOnly"
          Write-Host "完整路径: $fullPath"
          
          7z a -t7z -v1850M -mx=0 .\${{ env.REVISION_NAME }}_${{ env.REVISION }}.7z .\Win_ISO_Patching_Scripts\*.iso
          Write-Host "Split Archive Done..."

      - name: Step-6 Delete Old Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release delete ${{env.REVISION_NAME}} --cleanup-tag -y || true
        
      - name: Step-7 Build New Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          body: |
            ## ${{ env.REVISION_NAME }}_Update_${{ env.REVISION }}
            - **Update**:  ${{ env.FINAL_ARTIFACT_NAME }}
            
            - **Original Image**: zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.iso
            ---
            ### 📦 下载说明
            使用 7-Zip 进行分卷压缩（每卷 1650M）。
            **下载方式**:
            1. 下载所有 `.7z.001`, `.7z.002`, ... 等后缀的文件。
            2. 确保所有文件位于同一文件夹。
            3. 使用 7-Zip 解压 `.7z.001` 即可获得完整的 ISO 文件。
            ---
          tag_name: ${{ env.REVISION_NAME }}
          name: ${{ env.REVISION_NAME }}_${{ env.REVISION }}
          files: |
            ${{ env.REVISION_NAME }}_${{ env.REVISION }}.7z.*
