name: WIN10_22H2_amd64
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 14 * *'
permissions:
  contents: write
jobs:
  WIN10_22H2_amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Step-1 Initialize Workspace
        shell: pwsh
        working-directory: .
        run: |
          mkdir -Force src
          mkdir -Force dist_win10
      - name: Step-2 Checkout Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: .
        run: |
          git clone https://github.com/adavak/Win_ISO_Patching_Scripts.git
      - name: Step-3 Download from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        working-directory: ./Win_ISO_Patching_Scripts
        run: |
          gh release download Windows10ISO --repo yuanpeirong/UpdateWinISO --pattern "*38efd00d.7z.*" --dir ./
          7z x *.7z.001 -y
          Start-Sleep -Seconds 3
          Rename-Item -Path "*.iso" -NewName "win10src22h2.iso"
          Remove-Item -Path "*.7z.*" -Force
          Move-Item -Path "..\set\W10UI.ini" -Destination ".\W10UI.ini" -Force
          Move-Item -Path "..\set\W10UI.cmd" -Destination ".\W10UI.cmd" -Force
      - name: Step-4 Update By Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: ./Win_ISO_Patching_Scripts
        run: |
          .\Start.cmd
      - name: Step-5 Split Archive
        shell: pwsh
        working-directory: .
        run: |
          Remove-Item -Path ".\Win_ISO_Patching_Scripts\win10src22h2.iso" -Force -ErrorAction SilentlyContinue
          
          $iso = Get-ChildItem -Path ".\Win_ISO_Patching_Scripts" -Filter "*.iso" -File | Select-Object -First 1
          $hash = (Get-FileHash -Path $iso.FullName -Algorithm SHA256).Hash.ToLower()
          $hash8 = $hash.Substring($hash.Length - 8)
          $newName = "$($iso.BaseName)_$hash8.iso"
          $newPath = Join-Path -Path $iso.DirectoryName -ChildPath $newName
          Rename-Item -Path $iso.FullName -NewName $newName -Force
          $revisionName = "WIN10_22H2_amd64"
          $isoBaseName = $iso.BaseName
          $revision = $isoBaseName.Split('-')[0]
          
          $sizeInBytes =$iso.Length
          $sizeInMB =$sizeInBytes / 1MB
          $sizeInGB =$sizeInBytes / 1GB
          
          echo "ISO_SIZEMB=$("{0:N2}" -f$sizeInMB) MB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ISO_SIZEGB=$("{0:N2}" -f$sizeInGB) GB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          echo "ISO_NAME=$newName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ISO_PATH=$newPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ISO_REVISION=$revision" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "REVISION_NAME=$revisionName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "SHA256=$hash" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          Write-Host "文件名: $newName"
          Write-Host "文件路径: $newPath"
          Write-Host "版本: $revision"
          Write-Host "SHA256: $hash"
          
          $outputZipFileName = "${revisionName}-${revision}.7z"
          
          7z a -t7z -v1536M -mx=0 ".\dist_win10\$outputZipFileName" "$newPath"
          
          Write-Host "Generated archive: .\$outputZipFileName"
          Write-Host "Split Archive Done..."
          
      - name: Step-6 Delete Old Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release delete ${{env.REVISION_NAME}} --cleanup-tag -y || true
      - name: Step-7 Build New Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          body: |
            ## WIN10_22H2_amd64_Update-${{ env.ISO_REVISION }}
            - **ARTIFACT**: ${{ env.ISO_NAME }}
            - **SHA256**: ${{ env.SHA256 }}
            - **SIZE**: ${{ env.ISO_SIZEMB }} 、 ${{ env.ISO_SIZEGB }}
            - **ORIGINAL**: zh-cn_windows_10_consumer_editions_version_22h2_updated_oct_2025_x64_dvd_38efd00d.iso
            ---
            ### 📦 下载说明
            使用 7-Zip 进行分卷压缩（每卷 1280M）。
            **下载方式**:
            1. 下载所有 `.7z.001`, `.7z.002`, ... 等后缀的文件。
            2. 确保所有文件位于同一文件夹。
            3. 使用 7-Zip 解压 `.7z.001` 即可获得完整的 ISO 文件。
            4. 使用 `https://gh-proxy.com/` 加速下载
            ---
          tag_name: ${{ env.REVISION_NAME }}
          name: ${{ env.REVISION_NAME }}-${{ env.ISO_REVISION }}
          files: |
            .\dist_win10\${{ env.REVISION_NAME }}-${{ env.ISO_REVISION }}.7z.*
