name: Win10_LTSC2021_amd64

on: workflow_dispatch

permissions:
  contents: write
env:
  REVISION: '19044.7725'
  REVISION_NAME: Win10_LTSC2021_amd64
jobs:
  Win10_LTSC2021_amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        
      - name: Step-1 Initialize Workspace
        shell: pwsh
        working-directory: .
        run: |
          mkdir -Force src
          mkdir -Force dist

      - name: Step-2 Checkout Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: .
        run: |
          git clone https://github.com/adavak/Win_ISO_Patching_Scripts.git
          ls
          pwd
      - name: Step-3 Download from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        working-directory: ./src
        run: |
          #gh release download v1.0.0 --repo ${{ github.repository }} --pattern "*.7z.*" --dir ./
          #curl -L -o Win10LTSC2021amd64Original.iso
          
          curl -L -o zh-Win10LTSC2021amd64.7z.001 https://github.com/yuanpeirong/UpdateWinISO/releases/download/Windows10ISO/zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.7z.001
          curl -L -o zh-Win10LTSC2021amd64.7z.002 https://github.com/yuanpeirong/UpdateWinISO/releases/download/Windows10ISO/zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.7z.002
          curl -L -o zh-Win10LTSC2021amd64.7z.003 https://github.com/yuanpeirong/UpdateWinISO/releases/download/Windows10ISO/zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.7z.003

          7z x Win10LTSC2021amd64.7z.001 -y
          #4810M
          Rename-Item -Path "*.iso" -NewName "Win10LTSC2021amd64Original.iso"
          Remove-Item -Path "*.7z.*" -Force
          ls
          pwd
          
      - name: Step-4 Update By Win_ISO_Patching_Scripts
        shell: cmd
        working-directory: .
        run: |
          copy ".\set\W10UI.ini" ".\Win_ISO_Patching_Scripts\" /Y
          copy ".\set\W10UI.cmd" ".\Win_ISO_Patching_Scripts\" /Y
          move ".\src\Win10LTSC2021amd64Original.iso" ".\Win_ISO_Patching_Scripts\" /Y
          cd && dir /s
          
          .\Win_ISO_Patching_Scripts\Start.cmd
          
          cd && dir /s
        
      - name: Step-5 Split Archive
        shell: pwsh
        working-directory: .
        run: |
          Remove-Item -Path ".\Win_ISO_Patching_Scripts\Win10LTSC2021amd64Original.iso" -Force
          
          $file = Get-ChildItem -Path .\Win_ISO_Patching_Scripts -Filter "*.iso" -File | Select-Object -First 1
          $fileNameOnly =$file.Name
          $fullPath =$file.FullName
          Add-Content -Path $env:GITHUB_ENV -Value "FINAL_ARTIFACT_NAME=$fileNameOnly"
          Add-Content -Path $env:GITHUB_ENV -Value "FINAL_ARTIFACT_PATH=$fullPath"
          Write-Host "捕获到的文件名: $fileNameOnly"
          Write-Host "完整路径: $fullPath"
          
          7z a -t7z -v1650M -mx=0 .\${{ env.REVISION_NAME }}_${{ env.REVISION }}.7z .\Win_ISO_Patching_Scripts\*.iso
          Write-Host "Split Archive Done..."

      - name: Step-6 Delete Old Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release delete ${{env.REVISION_NAME}} --cleanup-tag -y || true
        
      - name: Step-7 Build New Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          body: |
            ## ${{ env.REVISION_NAME }}_Update_${{ env.REVISION }}
            - **Update**:  ${{ env.FINAL_ARTIFACT_NAME }}
            
            - **Original Image**: zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.iso
            ---
            ### 📦 下载说明
            使用 7-Zip 进行分卷压缩（每卷 1650M）。
            **下载方式**:
            1. 下载所有 `.7z.001`, `.7z.002`, ... 等后缀的文件。
            2. 确保所有文件位于同一文件夹。
            3. 使用 7-Zip 解压 `.7z.001` 即可获得完整的 ISO 文件。
            ---
          tag_name: ${{ env.REVISION_NAME }}
          name: ${{ env.REVISION_NAME }}_${{ env.REVISION }}
          files: |
            ${{ env.REVISION_NAME }}_${{ env.REVISION }}.7z.*
