name: Win11LTSC2024amd64
on: workflow_dispatch
permissions:
  contents: write
jobs:
  Win11LTSC2024amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Step-1 Initialize Workspace
        shell: pwsh
        working-directory: .
        run: |
          mkdir -Force src
          mkdir -Force dist
      - name: Step-2 Checkout Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: .
        run: |
          git clone https://github.com/adavak/Win_ISO_Patching_Scripts.git
      - name: Step-3 Download from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        working-directory: ./Win_ISO_Patching_Scripts
        run: |
          #gh release download v1.0.0 --repo ${{ github.repository }} --pattern "*.7z.*" --dir ./
          curl -L -o win11src.7z.001 https://github.com/yuanpeirong/UpdateWinISO/releases/download/Windows11ISO/zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.7z.001
          curl -L -o win11src.7z.002 https://github.com/yuanpeirong/UpdateWinISO/releases/download/Windows11ISO/zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.7z.002
          curl -L -o win11src.7z.003 https://github.com/yuanpeirong/UpdateWinISO/releases/download/Windows11ISO/zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.7z.003
          7z x win11src.7z.001 -y
          #5042M
          Start-Sleep -Seconds 3
          Rename-Item -Path "*.iso" -NewName "win11src.iso"
          Remove-Item -Path "*.7z.*" -Force
          Move-Item -Path "..\set\W10UI.ini" -Destination ".\W10UI.ini" -Force
          Move-Item -Path "..\set\W10UI.cmd" -Destination ".\W10UI.cmd" -Force
          
      - name: Step-4 Update By Win_ISO_Patching_Scripts
        shell: pwsh
        working-directory: .
        run: |
          .\Win_ISO_Patching_Scripts\Start.cmd

      - name: Step-5 Split Archive
        shell: pwsh
        working-directory: .
        run: |
          Remove-Item -Path ".\Win_ISO_Patching_Scripts\win11src.iso" -Force
          $file = Get-ChildItem -Path .\Win_ISO_Patching_Scripts -Filter "*.iso" -File | Select-Object -First 1
          $fileNameOnly = $file.Name
          $fullPath = $file.FullName
          $version = $fileNameOnly.Split('-')[0]
          Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT_NAME=$fileNameOnly"
          Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT_PATH=$fullPath"
          Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT_REVISION=$version"
          Add-Content -Path $env:GITHUB_ENV -Value "REVISION_NAME=WIN11LTSC2024amd64"
          Write-Host "完整文件名: ${{ env.ARTIFACT_NAME }}"
          Write-Host "完整路径: ${{ env.ARTIFACT_PATH }}"
          Write-Host "ARTIFACT_REVISION: ${{ env.ARTIFACT_REVISION }}"
          Write-Host "REVISION_NAME: ${{ env.REVISION_NAME }}"
          
          7z a -t7z -v1536M -mx=0 .\${{ env.REVISION_NAME }}-${{ env.ARTIFACT_REVISION }}.7z .\Win_ISO_Patching_Scripts\*.iso
          Write-Host "Split Archive Done..."

      - name: Step-6 Delete Old Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release delete ${{env.REVISION_NAME}} --cleanup-tag -y || true
        
      - name: Step-7 Build New Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          body:  
            ## ${{ env.REVISION_NAME }}-Update-${{ env.ARTIFACT_REVISION }}
            - **ARTIFACT**:  ${{ env.ARTIFACT_NAME }}
            - **ORIGINAL**: zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.iso
            ---
            ### 📦 下载说明
            使用 7-Zip 进行分卷压缩（每卷 1650M）。
            **下载方式**:
            1. 下载所有 `.7z.001`, `.7z.002`, ... 等后缀的文件。
            2. 确保所有文件位于同一文件夹。
            3. 使用 7-Zip 解压 `.7z.001` 即可获得完整的 ISO 文件。
            ---
          tag_name: ${{ env.REVISION_NAME }}
          name: ${{ env.REVISION_NAME }}-${{ env.ARTIFACT_REVISION }}
          files: *.7z.*
          